"""
header_footer_formatters.py

Last edited: 2026-7-31
"""
from collections.abc import Sequence
from pathlib import Path

from logduo.internals.engine.runtime_classes import RuntimeRecord
from logduo.utils.wrap.wrap_text import wrap_text


# --- _build_header_info_rows() -----------------------------------------------
def _build_auto_header_info_rows(
    *, runtime: RuntimeRecord, file_name: str, is_log_file: bool = True
) -> list[tuple[str | None, str]]:
    """
    Build info header rows.
    Returns:
        List of:
            (None, value)
                -> standalone title row
            (label, value)
                -> standard labeled metadata row
    No renderer-specific formatting is applied here.
    """
    rows: list[tuple[str | None, str]] = []
    if runtime.start_time_display is None:
        raise RuntimeError("LOGDUO INTERNAL ERROR: start_time_display not set.")

    # log files, log file name shown above time
    if is_log_file:
        # log file name
        rows.append((None, file_name))

        # --- started time row ---
        rows.append(("Logging started", runtime.start_time_display))

        # --- script name (if Logduo session initiated by script) ---
        if runtime.script_name:
            rows.append(("Generated by", runtime.script_name))

    # console
    else:
        # --- started time row ---
        rows.append(("Logging started", runtime.start_time_display))

        # --- script name (if Logduo session initiated by script) ---
        if runtime.script_name:
            rows.append(("Running script", runtime.script_name))

    return rows


# --- _build_auto_footer_info_rows() -------------------------------------------
def _build_auto_footer_info_rows(
    *,
    runtime: RuntimeRecord,
    is_main_sink: bool,
) -> list[tuple[str, str]]:
    """
    Build footer information rows.

    The logging end time is always included.

    Duration is included only for the main sink.
    The absolute script path is included only for script sessions.
    """
    if runtime.end_time_display is None:
        raise RuntimeError(
            "LOGDUO INTERNAL ERROR: end_time_display not set."
        )

    ended_value = runtime.end_time_display

    if is_main_sink and runtime.duration_display:
        ended_value += f" (duration {runtime.duration_display})"

    rows = [("Logging ended", ended_value)]

    if runtime.script_path_abs is not None:
        rows.append(("Script path", str(runtime.script_path_abs)))

    return rows


# --- _build_auto_footer_generated_file_lists() ---------------------------------
def _build_auto_footer_generated_file_lists(
    runtime: RuntimeRecord,
    *,
    include_jsonl: bool = True,
) -> tuple[
    str,
    list[str],
    list[str],
    list[str],
]:
    """
    Build display-ready file groups for the automatic footer.

    Returns:
        output_dir_path:
            Absolute path to the main output directory.

        output_dir_files:
            File paths relative to the main output directory.

        other_files:
            Absolute paths for existing files outside the main output directory.

        missing_files:
            Absolute paths for registered files not found on disk.

        Files using append mode include an ``(append)`` suffix.
    """
    output_dir_path = runtime.main_sink_log_dir_path_abs

    if output_dir_path is None:
        raise RuntimeError(
            "LOGDUO INTERNAL ERROR: main_sink_log_dir_path_abs not set."
        )

    output_dir_path = output_dir_path.absolute()

    output_dir_files: list[str] = []
    other_files: list[str] = []
    missing_files: list[str] = []

    for generated_file_record in runtime._get_file_list_in_cfr():
        file_path = generated_file_record.path.absolute()

        display_suffix = (
            " (append)"
            if generated_file_record.log_file_mode == "append"
            else ""
        )

        try:
            file_exists = file_path.exists()

            if (
                include_jsonl
                and generated_file_record.file_kind == "jsonl"
            ):
                file_exists = True

        except OSError:
            file_exists = False

        if not file_exists:
            missing_files.append(f"{file_path}{display_suffix}")
            continue

        if _path_is_within(
            path=file_path,
            parent=output_dir_path,
        ):
            relative_path = file_path.relative_to(output_dir_path)
            output_dir_files.append(f"{relative_path}{display_suffix}")
        else:
            other_files.append(f"{file_path}{display_suffix}")

    output_dir_files.sort(key=lambda value: value.casefold())
    other_files.sort(key=lambda value: value.casefold())
    missing_files.sort(key=lambda value: value.casefold())


    return (
        str(output_dir_path),
        output_dir_files,
        other_files,
        missing_files,
    )



# --- _path_is_within() -------------------------------------------------------
def _path_is_within(
    *,
    path: Path,
    parent: Path,
) -> bool:
    try:
        path.relative_to(parent)
    except ValueError:
        return False

    return True


# --- _build_wrapped_lines() ---------------------------------------------------
def _build_wrapped_lines(
    *,
    value: str,
    width: int | str,
    continuation_width: int | None = None,
    hanging_indent: int | None = None,
) -> list[str]:
    if width == "off":
        return [value]
    assert isinstance(width, int)
    return wrap_text(
        value, width=width, continuation_width=continuation_width, hanging_indent=hanging_indent
    )


# --- _derive_label_pad() --------------------------------------------------------
def _derive_label_pad(rows: Sequence[tuple[str | None, str]], num: int = 0) -> int:
    labels = [label for label, _ in rows if label is not None]
    if not labels:
        return 0
    max_width = max(max(len(label) for label in labels), num)
    return max_width


# --- _render_plain_label_value_row() ------------------------------------------
def _render_plain_label_value_row(
    *,
    label: str,
    value: str,
    label_pad: int,
) -> str:
    label_with_colon = f"{label}:"
    return f"{label_with_colon:<{label_pad + 1}}  {value}"
